### ISSUE TITLE
Handling large amount of receivers

### ISSUE THREAD

**Issue by TimFoerster** [gergo85/oc-news#31]
Hey,

I need to handle +10.000k receivers.
I try to find a solution that fits for every needs.
Therefore i would suggest to push the sendings to a queue.

**Comment by gergo85** [comment]
Thank you very much for this improvement. I will check it.

**Comment by WWRFresource** [comment]
Hi, I know this issue is closed but I need some help with the queue system. I have done some research to better understand how the Queue works but am still not sure how to actually use it in production.

Once my messages are queued, I understand I need to run a console command such as php artisan queue:work 

Is there a way to automate this step? 

Also, would it be possible to implement a setting that disables using the queue system? I only have perhaps 40-50 susbscribers at one time.

Thank you for a wonderful plugin and continued support.

**Comment by TimFoerster** [comment]
@WWRFresource Have a look in the settings, you can disable queueing.

**Comment by TimFoerster** [comment]
@WWRFresource Just set the queue driver as sync. Then all messages will be send directly.

**Comment by WWRFresource** [comment]
@TimFoerster Hey, thanks for the speedy reply. So I have switched my driver over to sync, which works as expected.

I still have questions about how to actually use the Queue system in production. Once I get my messages queued up, how do I send them without running console commands?

**Comment by TimFoerster** [comment]
There are multiple ways, all descripted in the docs.
I use it with cron jobs, which sends the command every minute.

**Comment by WWRFresource** [comment]
@TimFoerster I see now. I guess I'm starting to get off OctoberCMS/plugin functionality now, and more into Laravel/Cronjobs. Do you have time or are you willing to help me anymore? Perhaps via email or another method? Thanks again.

**Comment by TimFoerster** [comment]
come into [ocms slack chat](http://octobercms-slack.herokuapp.com/), I'm always there
